The exception :exc:`socket.timeout` is now an alias of :exc:`TimeoutError`.
